import PumpkinImage from '../assets/images/Abobora.png';
import RosemaryImage from '../assets/images/Alecrim.png';
import LettuceImage from '../assets/images/Alface.png';
import GarlicImage from '../assets/images/Alho.png';
import LeekImage from '../assets/images/AlhoPoro.png';
import EggplantImage from '../assets/images/Beringela.png';
import BrocoliImage from '../assets/images/Brocolis.png';
import OnionImage from '../assets/images/Cebola.png';
import ScallionImage from '../assets/images/Cebolinha.png';
import CilantroImage from '../assets/images/Coentro.png';
import CarrotImage from '../assets/images/Cenoura.png';
import CauliflowerImage from '../assets/images/CouveFlor.png';
import CucumberImage from '../assets/images/Pepino.png';
import PepperImage from '../assets/images/Pimenta.png';
import TomatoImage from '../assets/images/Tomate.png';
import SunflowerImage from '../assets/images/Girassol.png';
import StrawberryImage from '../assets/images/Morango.png';
import PeaImage from '../assets/images/Ervilha.png';
import CornImage from '../assets/images/Milho.png';
import MarigoldImage from '../assets/images/Tagete.png';
import NasturtiumImage from '../assets/images/Capuchinha.png';
import SageImage from '../assets/images/Salvia.png';
import MelonImage from '../assets/images/Melao.png';
import SpinachImage from '../assets/images/Espinafre.png';
import GreenBeanImage from '../assets/images/VagemFeijao.png';
import BasilImage from '../assets/images/Manjericao.png';
import OreganoImage from '../assets/images/Oregano.png';
import ParsleyImage from '../assets/images/Salsa.png';
import ThymeImage from '../assets/images/Tomilho.png';

export const mockdb: Vegetable[] = [
  {
    name: 'Pumpkin',
    companions: [
      'Lettuce',
      'Broccoli',
      'Nasturtium',
      'Cauliflower',
      'Pea',
      'Sunflower',
      'Corn',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: ['Broccoli', 'Cauliflower'],
    control: ['Nasturtium', 'Marigold'],
    specifications: {
      plantingSeason: 'Spring/Summer',
      harvest: '90-120 days',
      lightRequirement: 'Full sun',
      irrigation: 'Regular',
      soil: 'Fertile and well-drained',
      hardiness: 'Medium',
      lifeCycle: 'Annual',
      seedsPerHole: 3,
      plantSpacing: 100,
      rowSpacing: 150,
    },
    image: PumpkinImage,
  },
  {
    name: 'Rosemary',
    companions: [
      'Garlic',
      'Onion',
      'Carrot',
      'Cauliflower',
      'Pea',
      'Green Bean',
      'Strawberry',
      'Cucumber',
      'Pepper',
      'Tomato',
    ],
    incompatibles: [],
    control: [],
    specifications: {
      plantingSeason: 'Year-round',
      harvest: '60-90 days',
      lightRequirement: 'Full sun or partial shade',
      irrigation: 'Regular',
      soil: 'Fertile and well-drained',
      hardiness: 'High',
      lifeCycle: 'Perennial',
      seedsPerHole: 3,
      plantSpacing: 50,
      rowSpacing: 100,
    },
    image: RosemaryImage,
  },
  {
    name: 'Lettuce',
    companions: [
      'Beetroot',
      'Broccoli',
      'Onion',
      'Carrot',
      'Cilantro',
      'Cabbage',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Pepper',
      'Tomato',
    ],
    incompatibles: [],
    control: [],
    specifications: {
      plantingSeason: 'Year-round',
      harvest: '30-60 days',
      lightRequirement: 'Full sun or partial shade',
      irrigation: 'Regular',
      soil: 'Fertile and well-drained',
      hardiness: 'Medium',
      lifeCycle: 'Annual',
      seedsPerHole: 5,
      plantSpacing: 20,
      rowSpacing: 30,
    },
    image: LettuceImage,
  },
  {
    name: 'Garlic',
    companions: [
      'Rosemary',
      'Carrot',
      'Onion',
      'Cauliflower',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Pepper',
      'Tomato',
    ],
    incompatibles: ['Green beans', 'Peas'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: GarlicImage,
  },
  {
    name: 'Leek',
    companions: [
      'Lettuce',
      'Beetroot',
      'Onion',
      'Carrot',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: ['Green beans', 'Peas'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: LeekImage,
  },
  {
    name: 'Eggplant',
    companions: ['Rosemary', 'Broccoli', 'Green beans', 'Pepper', 'Tomato'],
    incompatibles: [],
    control: ['Marigold', 'Thyme'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: EggplantImage,
  },
  {
    name: 'Broccoli',
    companions: [
      'Squash',
      'Lettuce',
      'Eggplant',
      'Onion',
      'Cauliflower',
      'Pea',
      'Sunflower',
      'Melon',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: ['Strawberry', 'Pepper', 'Tomato'],
    control: ['Oregano'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: BrocoliImage,
  },
  {
    name: 'Nasturtium',
    companions: [
      'Squash',
      'Lettuce',
      'Broccoli',
      'Cauliflower',
      'Pea',
      'Sunflower',
      'Melon',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: [],
    control: ['Squash'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: NasturtiumImage,
  },
  {
    name: 'Onion',
    companions: [
      'Rosemary',
      'Lettuce',
      'Garlic',
      'Leek',
      'Broccoli',
      'Carrot',
      'Cauliflower',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Pepper',
      'Tomato',
    ],
    incompatibles: ['Green beans', 'Peas'],
    control: ['Marigold'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: OnionImage,
  },
  {
    name: 'Green Onion',
    companions: [
      'Lettuce',
      'Beetroot',
      'Carrot',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: ['Green beans', 'Peas'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: ScallionImage,
  },
  {
    name: 'Carrot',
    companions: [
      'Rosemary',
      'Lettuce',
      'Garlic',
      'Onion',
      'Cauliflower',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Pepper',
      'Tomato',
    ],
    incompatibles: [],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: CarrotImage,
  },
  {
    name: 'Cilantro',
    companions: [
      'Lettuce',
      'Beetroot',
      'Carrot',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: [],
    control: ['Spinach'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: CilantroImage,
  },
  {
    name: 'Cauliflower',
    companions: [
      'Squash',
      'Rosemary',
      'Broccoli',
      'Onion',
      'Pea',
      'Sunflower',
      'Melon',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: ['Squash', 'Strawberry', 'Pepper', 'Tomato'],
    control: ['Oregano'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: CauliflowerImage,
  },
  {
    name: 'Pea',
    companions: [
      'Squash',
      'Rosemary',
      'Lettuce',
      'Garlic',
      'Leek',
      'Broccoli',
      'Carrot',
      'Cauliflower',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Pepper',
      'Tomato',
    ],
    incompatibles: ['Garlic', 'Leek', 'Onion', 'Green Onion'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: PeaImage,
  },
  {
    name: 'Spinach',
    companions: [
      'Lettuce',
      'Beetroot',
      'Onion',
      'Carrot',
      'Cilantro',
      'Pea',
      'Strawberry',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: [],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: SpinachImage,
  },
  {
    name: 'Green Bean',
    companions: ['Rosemary', 'Eggplant', 'Corn', 'Tomato'],
    incompatibles: [
      'Garlic',
      'Leek',
      'Onion',
      'Green Onion',
      'Pepper',
      'Marigold',
    ],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: GreenBeanImage,
  },
  {
    name: 'Sunflower',
    companions: [
      'Squash',
      'Broccoli',
      'Nasturtium',
      'Cauliflower',
      'Pea',
      'Melon',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: [],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: SunflowerImage,
  },
  {
    name: 'Basil',
    companions: [
      'Lettuce',
      'Beetroot',
      'Carrot',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: [],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: BasilImage,
  },
  {
    name: 'Melon',
    companions: [
      'Broccoli',
      'Nasturtium',
      'Cauliflower',
      'Sunflower',
      'Tomato',
    ],
    incompatibles: [],
    control: ['Nasturtium'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: MelonImage,
  },
  {
    name: 'Corn',
    companions: ['Squash', 'Green Bean', 'Sunflower', 'Tomato'],
    incompatibles: [],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: CornImage,
  },
  {
    name: 'Strawberry',
    companions: [
      'Rosemary',
      'Lettuce',
      'Garlic',
      'Onion',
      'Spinach',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: ['Broccoli', 'Cauliflower'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: StrawberryImage,
  },
  {
    name: 'Oregano',
    companions: [
      'Lettuce',
      'Beetroot',
      'Carrot',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Tomato',
    ],
    incompatibles: ['Potato'],
    control: ['Broccoli', 'Cauliflower'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: OreganoImage,
  },
  {
    name: 'Cucumber',
    companions: [
      'Squash',
      'Rosemary',
      'Lettuce',
      'Garlic',
      'Leek',
      'Broccoli',
      'Carrot',
      'Cauliflower',
      'Pea',
      'Strawberry',
      'Pepper',
      'Tomato',
    ],
    incompatibles: ['Potato'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: CucumberImage,
  },
  {
    name: 'Pepper',
    companions: ['Rosemary', 'Eggplant', 'Green Bean', 'Tomato'],
    incompatibles: ['Broccoli', 'Cauliflower'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: PepperImage,
  },
  {
    name: 'Parsley',
    companions: [
      'Lettuce',
      'Beetroot',
      'Carrot',
      'Pea',
      'Spinach',
      'Strawberry',
      'Cucumber',
      'Tomato', // Assumindo que "Tom" se refere a "Tomato"
    ],
    incompatibles: [],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: ParsleyImage,
  },
  {
    name: 'Sage',
    companions: ['Broccoli', 'Carrot', 'Cauliflower'],
    incompatibles: ['Cucumber'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: SageImage,
  },
  {
    name: 'Marigold',
    companions: ['Melon', 'Tomato'],
    incompatibles: [
      'Green Bean', // Ajustado de "Feijão Vargem" para o equivalente em inglês
    ],
    control: [
      'Squash', // Supondo que "Abobora" se refere a "Squash"
      'Eggplant', // "Beringela" ajustado para "Eggplant"
    ],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: MarigoldImage,
  },
  {
    name: 'Tomato',
    companions: [
      'Garlic',
      'Leek',
      'Eggplant',
      'Nasturtium',
      'Onion',
      'Green Onion',
      'Green Bean',
      'Melon',
      'Oregano',
      'Cucumber',
      'Pepper',
      'Marigold',
    ],
    incompatibles: ['Broccoli', 'Cauliflower', 'Corn'],
    control: [],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: TomatoImage,
  },
  {
    name: 'Thyme',
    companions: ['Broccoli', 'Cauliflower', 'Strawberry'],
    incompatibles: [],
    control: ['Eggplant'],
    specifications: {
      plantingSeason: '',
      harvest: '',
      lightRequirement: '',
      irrigation: '',
      soil: '',
      hardiness: '',
      lifeCycle: '',
      seedsPerHole: '',
      plantSpacing: '',
      rowSpacing: '',
    },
    image: ThymeImage,
  },
];
